const AppConst = {
  AGE_MIN: 14,
  AGE_MAX: 101,
  NAME_MIN_LENGTH: 3,
  NAME_MAX_LENGTH: 50,
  USERNAME_MIN_LENGTH: 4,
  USERNAME_MAX_LENGTH: 15,
  PASSWORD_MIN_LENGTH: 6,
  PASSWORD_MAX_LENGTH: 20,
  OFFSET_DEFAULT_VALUE: 0,
  LIMIT_DEFAULT_VALUE: 20,

  DB_URL: '127.0.0.1:27017/firstproject'
}

module.exports = AppConst;
